# Generated by Django 5.2 on 2025-04-10 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ad",
            name="category",
            field=models.CharField(
                choices=[
                    ("т", "техника"),
                    ("м", "мебель"),
                    ("о", "одежда"),
                    ("к", "книги"),
                    ("п", "прочее"),
                ],
                default="п",
                max_length=1,
                verbose_name="Категория",
            ),
        ),
        migrations.AlterField(
            model_name="ad",
            name="condition",
            field=models.CharField(
                choices=[("н", "новый"), ("б", "б/у")],
                default="н",
                max_length=1,
                verbose_name="Состояние",
            ),
        ),
    ]
