# Generated by Django 5.2 on 2025-04-11 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_app", "0002_alter_ad_category_alter_ad_condition"),
    ]

    operations = [
        migrations.AddField(
            model_name="ad",
            name="image",
            field=models.ImageField(
                blank=True, upload_to="", verbose_name="Изображения"
            ),
        ),
    ]
