# Generated by Django 5.2 on 2025-04-11 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_app", "0004_alter_ad_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ad",
            name="image",
            field=models.ImageField(upload_to="", verbose_name="Изображения"),
        ),
    ]
