# Generated by Django 5.2 on 2025-04-14 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_app", "0005_alter_ad_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="ad",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="ad",
            name="image",
            field=models.ImageField(
                blank=True, upload_to="", verbose_name="Изображение"
            ),
        ),
    ]
