# Generated by Django 5.2 on 2025-04-16 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_app", "0007_ad_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExchangeProposal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comment", models.TextField(verbose_name="Комментарий")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("expect", "ожидает"),
                            ("accepted", "принята"),
                            ("rejected", "отклонена"),
                        ],
                        default="expect",
                        max_length=10,
                        verbose_name="Статус",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "ad_receiver",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ad_rec",
                        to="my_app.ad",
                        verbose_name="Id объявления-получателя",
                    ),
                ),
                (
                    "ad_sender",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ad_send",
                        to="my_app.ad",
                        verbose_name="Id объявления-отправителя",
                    ),
                ),
            ],
        ),
    ]
