# Generated by Django 5.2 on 2025-04-18 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("my_app", "0009_exchangeproposal_user_receiver_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exchangeproposal",
            name="user_receiver",
        ),
        migrations.RemoveField(
            model_name="exchangeproposal",
            name="user_sender",
        ),
    ]
